// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jequlpvidimqlygeoxmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplcXVscHZpZGltcWx5Z2VveG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzM2MDMsImV4cCI6MjA2MDc0OTYwM30.1tYgDKaZGuWNAN_4ZDVxXJdU6jJ8N16kNiHinTM7_l8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);